FROM --platform=linux/amd64 node:22.2.0-alpine

ENV NODE_ENV "development"

WORKDIR /app

COPY pkg-nodejs ../pkg-nodejs

COPY app .

RUN npm install -g npm

RUN npm install

CMD npm run start:dev

EXPOSE 4000
