apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appName}}-{{.Values.envName}}-config
  namespace: {{.Values.namespace}}
data:
  AWS_REGION: {{.Values.AWS_REGION}}
  KMS_CREATE_ID: {{.Values.KMS_CREATE_ID}}
  KMS_CREATE_KEY: {{.Values.KMS_CREATE_KEY}}
  KMS_SIGN_ID: {{.Values.KMS_SIGN_ID}}
  KMS_SIGN_KEY: {{.Values.KMS_SIGN_KEY}}