apiVersion: v1  
kind: Secret  
metadata:  
  name: {{.Values.appName}}-{{.Values.envName}}-dockercfg  
  annotations:  
    harness.io/skip-versioning: "true"  
data:  
  .dockercfg: {{.Values.dockercfg}}  
type: kubernetes.io/dockercfg